name        : libquvi-scripts
version     : 0.9.20131130
release     : 2
source      :
    - https://nchc.dl.sourceforge.net/project/quvi/0.9/libquvi-scripts/libquvi-scripts-0.9.20131130.tar.xz : 17f21f9fac10cf60af2741f2c86a8ffd8007aa334d1eb78ff6ece130cb3777e3
license     : AGPL-3.0
component   : programming
summary     : Lua scripts for libquvi
builddeps   :
    - pkgconfig(libproxy-1.0)
    - pkgconfig(lua-5.1)
description : |
    libquvi-scripts contains the Lua scripts for libquvi that it uses to parse the media properties.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
